import Header from "@/components/layout/Header/Header";
import TopBar from "@/components/ui/TopBar/TopBar";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Detailing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TopBar />

      <Header />

    </>
  );
}
