
import Benefits from "@/components/layout/Benefits/Benefits";
import Faq from "@/components/layout/FAQ/Faq";
import Hero from "@/components/layout/Hero/Hero";
import RandomCards from "@/components/layout/RandomCards/RandomCards";
import Reviews from "@/components/layout/Reviews/Reviews";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Detailing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <Benefits />
      <RandomCards />
      <Faq />
      <Reviews />
    </>
  );
}
