name: Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

<<<<<<< HEAD
=======
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.15'

>>>>>>> 9ee56f8f0ee65c9a5e58b4619fdbd90b6ae3786e
      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
<<<<<<< HEAD
	    export PATH=$HOME/.local/bin:$PATH
=======
>>>>>>> 9ee56f8f0ee65c9a5e58b4619fdbd90b6ae3786e
            cd /home/s/sheyhan14/detailing/detailing_frontend
            git pull
            npm install
            npm run build
            pm2 restart detailing.uz
